### ISSUE TITLE
Exception quando o CEP não possui logradouro

### ISSUE THREAD

**Issue by betoecomp** [jansenfelipe/cep-gratis#1]
Nos casos em que um único CEP é para toda a cidade (cidades do interior, por exemplo) a consulta retorna um Exception pelo fato de não ter encontrado um logradouro. Mas na verdade está correto, pois para esses CEPs só é retornada a cidade e UF.

Sugiro a remoção destas 2 linhas:
```
if ($resposta['logradouro'] == "")
    throw new Exception('Logradouro não encontrado');
```
E talvez testar pela existência da cidade no resultado ao invés do logradouro.

**Comment by jansenfelipe** [comment]
Bem observado @betoecomp ! Você pode passar um CEP que cai no caso relatado?

**Comment by betoecomp** [comment]
Parabéns pelo plugin @jansenfelipe! 
Sim, eu testei com 48110000 de Catu (BA) e 42700000 de Lauro de Freitas (BA). No site do http://m.correios.com.br/movel/buscaCepConfirma.do ele exibe os CEPS corretamente das cidades.

**Comment by jansenfelipe** [comment]
Obrigado @betoecomp ! Pra falar verdade, já está na hora de uma v2.0 desse package. rs

O problema é que retirando as linhas mencionadas creio que não resolveria pois na linha 44 executa um "explode()".. Teria que testar melhor..

Vou deixar essa issue aberta pois, até amanha vou lançar a v2 com essa questão corrigida.

**Comment by betoecomp** [comment]
Como o explode() aceita receber string vazia ou NULL como segundo parâmetro e logo depois você também faz um if, então não deu problema retirando elas.

Talvez para ficar mais correto:
```php
if ($resposta['logradouro']) {
    $aux = explode(" - ", $resposta['logradouro']);
    if (count($aux) == 2) 
        $resposta['logradouro'] = $aux[0];
}
```

**Comment by jansenfelipe** [comment]
Uai, bom demais! Manda aí um pull request no branch com a alteração que eu aceito aqui ;)
Abraço!
