### ISSUE TITLE
 The current node list is empty.

### ISSUE THREAD

**Issue by ianitsky** [jansenfelipe/cep-gratis#14]
Olá.

Estou tendo um pequeno problema, com este bundle, mas só em produçao:

Ele me retorna o seguinte erro
 The current node list is empty.

Isso com qualquer cep.
Já teve esse problema? Saberia o que pode ser?

Obrigado

**Comment by jansenfelipe** [comment]
Ola @ianitsky tem mais detalhes do erro? em qual linha?

**Comment by ianitsky** [comment]
Olá @jansenfelipe , eu investiguei um pouco e descobri que é o retorno dos correios.
É um erro do $crawler.

Talvez tenham mudado a página? 

Desativei o provider dos correios e funcionou ok.
