### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by Matheus-Lima** [jansenfelipe/cep-gratis#3]
Olá, fui usar o pacote no Laravel 4.2 e está retornando o erro abaixo.

Coloquei o ServiceProvider e criei a alias no app.php, porem retorna o erro abaixo.

Call to undefined method JansenFelipe\CepGratis\CepGratis::consultar()

**Comment by jansenfelipe** [comment]
Olá @Matheus-Lima! No L4, chamar apenas `CepGratis::consultar($cep)` não funciona?

**Comment by Matheus-Lima** [comment]
Pois é @jansenfelipe, não funciona.
Até criei um projeto novo para testar e não adiantou.

**Comment by Matheus-Lima** [comment]
@jansenfelipe, consegui aqui.

Tive que colocar o: use \JansenFelipe\CepGratis\CepGratis as CepGratis;

Muito obrigado pelo pacote e pela atenção.
