### ISSUE TITLE
Nomes de bairros longos são cortados

### ISSUE THREAD

**Issue by hevertonfreitas** [jansenfelipe/cep-gratis#5]
Alguns CEPs de bairros com nomes muito longos, como por exemplo os seguintes CEPs, estão vindo cortados em vinte e poucos caracteres:

87509-230
87509-300
29212-315
06514-200

Acredito que seja uma limitação na exibição da quantidade de caracteres no HTML do site dos Correios. Posso tentar escrever uma alteração, mas isso implicaria em mudar a URL da requisição que é feita nos Correios.

**Comment by jansenfelipe** [comment]
Olá @hevertonfreitas! O Correios alterou novamente o site e hoje lancei a v2.0.4 com a correção.
Agora os bairros com nome longo está retornando normalmente.

Obrigado pelo report!
