### ISSUE TITLE
Erro quando o CEP buscado não existe

### ISSUE THREAD

**Issue by nunesbeto** [jansenfelipe/cep-gratis#7]
Ao tentar buscarmos um CEP que não existe, encontramos o seguinte erro:

```
InvalidArgumentException in Crawler.php line 566:
The current node list is empty.
```

**Comment by jansenfelipe** [comment]
Corrigido na v3.0.1 https://github.com/jansenfelipe/cep-gratis/pull/8
Obrigado!!
